name: Dockerize

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    uses: axieinfinity/workflows-samples/.github/workflows/security-basic-scan.yml@main

  docker:
    needs: scan
    uses: axieinfinity/workflows-samples/.github/workflows/docker-build-submodule.yml@main
    with:
      checkout_submodules: true
      image_repository: gcr.io/test-servers-256610/bridge-cleaner
    secrets: inherit